package game

import (
	"math"
)

var Directions = [][]int{
	{1, 0},
	{0, 1},
	{-1, 0},
	{0, -1},
}

func GetManhattanDistance(t1, t2 *Tile) int {
	dx := math.Abs(float64(t1.X - t2.X))
	dy := math.Abs(float64(t1.Y - t2.Y))
	return int(dx + dy)
}

func IsWall(row int, col int) bool {
	if row <= 0 || col <= 0 {
		return true
	}

	if col >= MapColCount-1 || row >= MapRowCount-1 {
		return true
	}

	return false
}

var funnyBotNames = []string{
	"Sir Laughs-a-Lot",
	"Captain Cranky",
	"Waffles the Destroyer",
	"Unit 404-Error",
	"Ctrl-Alt-Defeat",
	"Binary Bob",
	"Codey McCodeface",
	"The Algorithm Formerly Known As",
	"Byte Me",
	"Data Disaster",
	"GiggleGear",
	"Jokesmith 5000",
	"Sillytron",
	"The Great Debugger",
	"Mr. Roboto's Nephew",
	"Processor Puns",
	"Floppy Disk Flip",
	"Kernel Kook",
	"Logic Leaper",
	"The Ram-bling Man",
	"Socket Sock Puppet",
	"Chip 'n' Dale's Pal",
	"Circuit Board Chuckles",
	"Dr. Quirk",
	"Auto-Tune Andy",
	"Macro Mayhem",
	"The Caffeinated Compiler",
	"Syntax Snort",
	"Hardware Hilarity",
	"The Giggleplex",
	"Ping Pong Proxy",
	"Agent Anti-Gravity",
	"Recursive Rhonda",
	"Pixelated Pete",
	"The Glitch Whisperer",
	"Fuzzy Logic Larry",
	"The Spam-tastic",
	"Electric Eel-vis",
	"Irony I.O.",
	"Zero-Gravity Zen",
	"The Bot Who Could",
	"Bleep Blop Betty",
	"Wired Weirdo",
	"The Silent Screamer",
	"Manual Mode Mandy",
	"The Infinite Loophole",
	"Error Express",
	"Static Steve",
	"Dynamo Dave",
	"The Robot Next Door",
	"Turing Test Troll",
	"Quantum Quip",
	"Vector Victor",
	"The Jitterbug Bot",
	"Cable Guy Carl",
	"Power Down Pete",
	"The Friendly Firewall",
	"Digital Doodle",
	"The Uncanny Valley Girl",
	"Protocol Pal",
	"Binary Baffler",
	"The Rogue Router",
	"Spam-a-Lot Sam",
	"The Chatty Cache",
	"Whiskey Tango Foxtrot Bot",
	"The Hyper-Link Hooligan",
	"Agile Agnes",
	"Scrum Master Stan",
	"The DevOps Devil",
	"Cloudy with a Chance of Code",
	"The Server Sarcasm",
	"Patch Panel Paul",
	"The Modem Maverick",
	"Keylogger Kevin",
	"The Phishing Phantom",
	"Crypto Clarence",
	"Hash House Harriett",
	"Blockchain Buddy",
	"Wallet Wacko",
	"Decentralized Debra",
	"Mining Matt",
	"Token Terry",
	"The NFT Noodler",
	"Smart Contract Sammy",
	"The Oracle Oddball",
	"Big Data Bertha",
	"Machine Learning Marvin",
	"Neural Network Nick",
	"The Deep Learning Dude",
	"A.I. Amuse",
	"Predictive Pamela",
	"The Cog-nitive Comic",
	"Robot Rickshaw",
	"Automatic Alphonse",
	"Cyber Sidewalk",
	"Digital Darling",
	"The Electronic Elf",
	"Giga Gary",
	"Tera Tina",
	"Peta Paul",
	"Exa Ellie",
	"Zetta Zane",
	"Yotta Yvonne",
	"Kilobyte Kyle",
	"Megabyte Molly",
	"Gigahertz Gus",
	"Terahertz Tess",
	"The Nanobot Nuisance",
	"Pico Paulie",
	"Femto Fiona",
	"Atto Al",
	"The Jiggling Jumper",
	"The Wobbling Widget",
	"Snarky Sparky",
	"The Witty Wire",
	"Zenith Zapper",
	"Omega Outburst",
	"The Gamma Goofball",
	"Delta Drone",
	"The Beta Blunder",
	"Alpha Amigo",
	"Echo Effigy",
	"Foxtrot Flop",
	"Hotel Hilarity",
	"India Inkwell",
	"Juliette Jester",
	"Kilo Kickstart",
	"Lima Limbo",
	"Mike Mischief",
	"November Noodle",
	"Oscar Oops",
	"Papa Pout",
	"Quebec Quip",
	"Romeo Ruckus",
	"Sierra Snicker",
	"Tango Tickle",
	"Uniform Unrest",
	"Victor Vex",
	"Whiskey Whoops",
	"X-ray Xenon",
	"Yankee Yawn",
	"Zulu Zoomer",
	"The Hypertext Hoot",
	"The Cookie Crumbler",
	"The Spam Filter Fail",
	"Web Weaver Wanda",
	"The Browser Blunderer",
	"Link Lout",
	"URL Ulysses",
	"The DNS Ditz",
	"The Proxy Prankster",
	"Firewall Fred",
	"The Router Rascal",
	"Modem Moppet",
	"Gateway Goof",
	"The Hub Harvester",
	"Switcheroo Sue",
	"The Mesh Mess",
	"Wi-Fi Wacko",
	"The Bluetooth Bozo",
	"Infrared Iggy",
	"The Satellite Silly",
	"Transistor Tina",
	"Resistor Reggie",
	"Capacitor Carl",
	"Inductor Isaac",
	"Diode Dave",
	"Zener Zone",
	"The Transducer Trickster",
	"Oscillator Ollie",
	"Amplifier Amy",
	"Filter Finn",
	"Mixer Max",
	"The Detector Dummy",
	"The Emitter Elf",
	"Receiver Ralph",
	"Transmitter Tom",
	"The Antenna Antics",
	"Waveguide Wally",
	"The Circulator Clown",
	"Isolator Izzy",
	"Coupler Connie",
	"The Attenuator Ace",
	"Terminator Terry",
	"The Load Laugher",
	"Spectrum Steve",
	"Frequency Fran",
	"The Wavelength Wonder",
	"Amplitude Andy",
	"Phase Philip",
	"The Modulation Mime",
	"Demodulator Dee",
	"The Codec Comic",
	"Codec Carl",
	"The Packet Prank",
	"Frame Funster",
	"Segment Sammy",
	"The Datagram Droll",
	"PDU Pete",
	"The Service Setter",
	"Interface Ivan",
	"The Port Punster",
	"Socket Sam",
	"Bindy Bot",
	"Listen Lou",
	"The Acceptable Accused",
	"Connect Connie",
	"The Send Sensation",
	"Receive Renee",
	"Close Call Cliff",
	"The Shutdown Shenanigan",
	"Reboot Ricky",
	"Restart Reggie",
	"Sleepy System Sam",
	"Hibernate Harry",
	"The Suspend Spectacle",
	"Wake-up Wanda",
	"The Log Llama",
	"Debug Derek",
	"Breakpoint Benny",
	"The Watchpoint Waggish",
	"Call Stack Carl",
	"The Heap Hooray",
	"Stack Sammy",
	"The Pointer Prankster",
	"Reference Ricky",
	"The Garbage Collection Guy",
	"Mutex Mandy",
	"The Semaphore Silly",
	"Thread Titter",
	"The Process Punster",
	"Fork Fred",
	"Exec Elsie",
	"The Wait Wiggler",
	"Kill Kooky",
	"The Zombie Zest",
	"Orphan Ollie",
	"Daemon Delight",
	"The Background Buffoon",
	"Foreground Freddie",
	"The Shell Shock",
	"Bash Betty",
	"The Script Scamp",
	"Pipeline Pam",
	"The Redirection Rogue",
	"Input Iggy",
	"Output Ollie",
	"Error Ernie",
	"The Command Comic",
	"Argument Art",
	"Option Oswald",
	"The Flag Flapper",
	"Parameter Patty",
	"The Variable Villain",
	"Constant Charlie",
	"The Type Tease",
	"Function Felix",
	"The Method Mirth",
	"Class Clown",
	"The Object Oddity",
	"Instance Izzy",
	"The Inheritance Idiot",
	"Polymorphism Pam",
	"The Encapsulation Eccentric",
	"Abstraction Ace",
	"The Interface Intruder",
	"Package Prankster",
	"The Module Merrymaker",
	"Library Larry",
	"The Framework Fool",
	"API Ape",
	"The SDK Shenanigan",
	"The IDE Idyll",
	"Compiler Connie",
	"The Linker Laughter",
	"Loader Lou",
	"The Runtime Riot",
}
